//   post {
//         always {
//             archiveArtifacts artifacts: 'Source-Code/target/*.jar', allowEmptyArchive: true
//             cleanWs()
//         }
//         failure {
//             mail to: 'manoahmad97@gmail.com',
//                  subject: 'Jenkins Build Failed: PetClinic',
//                  body: 'The build has failed. Please check the Jenkins logs.'
//         }
//     }
// }

pipeline {
    agent any

    environment {
        IMAGE_NAME      = "mohanedahmed/spring-petclinic"
        IMAGE_TAG       = "${env.BUILD_ID}"
        RDS_ENDPOINT    = "<rds_endpoint>"
        GITHUB_REPO     = "https://github.com/MuhanedAhmed/test"
    }

    stages {
        stage('Checkout Repository') {
            steps {
                echo "Cloning the GitHub repository..."
                git branch: 'main', url: "${env.GITHUB_REPO}"
            }
        }

        stage('Build with Maven') {
            steps {
                dir('Source-Code') {
                    echo "Building the application with Maven..."
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                dir('Docker-Part') {
                    echo "Building Docker image..."
                    sh 'cp ../Source-Code/target/spring-petclinic-*.jar app.jar'
                    sh "docker build -t ${env.IMAGE_NAME}:${env.IMAGE_TAG} ."

                    echo "Logging into Docker Hub..."
                    withCredentials([usernamePassword(credentialsId: 'myDockerHub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                        sh "docker push ${env.IMAGE_NAME}:${env.IMAGE_TAG}"
                    }
                }
            }
        }

        stage('Deploy Application with Ansible') {
            steps {
                dir('Ansible-Part') {
                    echo "Deploying application using Ansible..."
                    sh """ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory setup_backend.yaml --tags app_deployment \
                        -e docker_image='${env.IMAGE_NAME}:${env.IMAGE_TAG}' \
                        -e rds_endpoint='${env.RDS_ENDPOINT}'
                        """
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed - cleaning up'
            cleanWs()
        }
        success {
            echo "Pipeline executed successfully."
        }
        failure {
            echo "Pipeline failed. Check the logs."
        }
    }
}